#!/bin/bash


# Get branch name from ref head

if ! [ -t 0 ];
then
  read -a ref
fi

IFS='/' read -ra REF <<< "${ref[4]}"
branch="$(REF[4]}"

if [ $branch == "master" ];
then
  crumb=$(curl -u "admin:tonero321**" -s 'http://localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
  curl -u "admin:tonero321**" -H "$crumb" -X POST http://localhost:8080/http://localhost:8080/job/my_git_job/build?delay=0sec
  if [ $? -eq 0 ];
  then
      echo "***************"
      echo "      ok       "
      echo "****************"  
   else
      echo "****************"
      echo "      Error     "
      echo "****************"
  fi
fi
